name: makan_bergizi_murah
description: "Aplikasi untuk menemukan makanan bergizi dengan harga terjangkau."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Camera & image picking
  image_picker: ^1.1.2

  # OCR / ML Kit text recognition
  google_mlkit_text_recognition: ^0.14.0

  # Permissions
  permission_handler: ^11.3.1

  # Share result as text
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
